# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fd0f51602e72bd5d953e86718f4d5c398e9bdbc31aa84b55b9e93baaa58113d351fe8848543f2f394661055487d10af142b318f441d432c092fd55fa00a7860

test:
  secret_key_base: 3a9de04e99ec9c287f647958fc4b7d72dbf93ffdd3168c40311dafdafb7fd54d13d4b8bd79b1bb894470e53a942f02ff7837d17e884b37781a0903c804ee35bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
